### ISSUE TITLE
confused tab persistence?

### ISSUE THREAD

**Issue by alanruttenberg** [YASGUI/YASGUI#60] opened 2015-05-23 05:37 UTC
I'm getting cases where a tab gets more than one yasqe on re-opening. Maybe something in persisting? Screen snap below. Perhaps relevant: I was doing the same query against two different endpoints in different tabs.

![screen shot 2015-05-23 at 1 35 10 am](https://cloud.githubusercontent.com/assets/241934/7782555/2b99d852-00ec-11e5-8b81-58444a3202c7.png)

**Comment by alanruttenberg** [comment] 2015-05-23 05:45
Another hint (just noticed this). The first time the tab is viewed there is a single yasqe. Each time I switch to another tab and back another one is added (I just clicked my way to having 7)

**Comment by LaurensRietveld** [comment] 2015-05-23 08:55
Strange, I can't seem to reproduce this issue. I remember having this similar behaviour before (about a month ago), but fixed that one. 

What I remember about the previous bug:
There is a check which draws YASQE when the tab content is drawn. This is for performance reasons, as we don't want to instantiate YASQE when the tab is instantiated (as a tab may remain closed for the rest of that particular session). For this particular bug, the check failed to detect whether YASQE was drawn already, and it simply drawed the tab content again.

Does this information help in finding a reproducable bug scenario?

**Comment by LaurensRietveld** [comment] 2015-06-21 14:55
Hi @alanruttenberg , did you encounter this issue recently as well? I haven't, so I'm inclined to close this ticket

**Comment by LaurensRietveld** [comment] 2015-07-02 16:53
cannot reproduce

**Closed by LaurensRietveld** 2015-07-02 16:53 UTC
