### ISSUE TITLE
Missing require('jquery-ui/sortable') in main.js?

### ISSUE THREAD

**Issue by alanruttenberg** [YASGUI/YASGUI#55] opened 2015-05-11 20:56 UTC
I was getting an error on table redraw when (trying) to run from the repo. That fixed it. Stumbling around I also updated to Datatables in YASR  and Jquery everywhere which fixed an earlier problem. Now local seems to work as as well as yasgui.org 

Is it possible that some other things are not checked in? If so I would be grateful if they could be.

Thanks,
Alan

**Comment by LaurensRietveld** [comment] 2015-05-11 21:08
Cannot reproduce this one as well. (again, cloned YASGUI, and ran `npm install` and `gulp serve`)

**Comment by LaurensRietveld** [comment] 2015-06-21 15:03
related to https://github.com/YASGUI/YASR/issues/71. closing this one as well

**Closed by LaurensRietveld** 2015-06-21 15:03 UTC
